### ISSUE TITLE
declare-queue should allow empty name

### ISSUE THREAD

**Issue by abraxxa** [retupmoca/P6-Net-AMQP#13]
So the AMQP broker generates a queue name. That's useful for non-durable, auto-delete queues.
In that case Net::AMQP::Queue should fetch the generated name after a successful declare and populate its name attribute with the broker assigned name.

**Comment by jonathanstowe** [comment]
I thought it did to be honest, let me check.

**Comment by jonathanstowe** [comment]
https://github.com/retupmoca/P6-Net-AMQP/commit/639361d1c07efff93756aa374b44bc1bfc196fca should have implemented it (and it is tested for,) so you will need to supply some code that doesn't work as expected.

**Comment by abraxxa** [comment]
Calling declare-queue fails for me with an invalid number of arguments error. It seems passing an empty string works but I'd prefer passing none ninstead.

**Comment by jonathanstowe** [comment]
A patch to make `declare-queue` a multi with samewith("") would work fine, I'll take a peek at some point.

**Comment by abraxxa** [comment]
Thanks!
Is a multi-sub really required to allow undef and ''?

**Comment by jonathanstowe** [comment]
well, an alternative would be to provide the method with a default of "" for the name. I prefer multis :)

**Comment by jonathanstowe** [comment]
This is out in the v0.1.5  sorry it took so long, I forgot about it :)

**Comment by abraxxa** [comment]
The longer syntax where you can supply passive and durable still doesn't allow passing of an undefined name, '' works as a workaround.

**Comment by jonathanstowe** [comment]
Are you sure?  I've just added a test that does ```$channel.declare-queue(:durable, :exclusive)``` and it  works fine.  You'll probably want to make sure you've got  the latest version (which is 0.1.9 now)/

**Comment by abraxxa** [comment]
I've used the following syntax:
```
my $q = $channel.declare-queue(
        '',
        passive     => False,
        durable     => False,
        exclusive   => True,
        auto-delete => True,
    ).result;
```

**Comment by abraxxa** [comment]
I've used the following syntax:
```
my $q = $channel.declare-queue(
        '',
        passive     => False,
        durable     => False,
        exclusive   => True,
        auto-delete => True,
    ).result;
```

**Comment by jonathanstowe** [comment]
You shouldn't need to do that  ```$channel.declare-queue(:exclusive, :auto-delete)``` should work fine.

**Comment by abraxxa** [comment]
As neither a type nor a default value is specified in the method signature I wasn't sure what they will end up with.
