### ISSUE TITLE
Can't get prefetch to work

### ISSUE THREAD

**Issue by abraxxa** [retupmoca/P6-Net-AMQP#18]
I've added
```
$channel.qos(10, 10);
say 'prefetch enabled';
```
just after the $channel got defined in the example but this leads to the following error short afterwards:
```
prefetch enabled
Unhandled exception in code scheduled on thread 7
Cannot assign to an immutable value
  in block  at /home/user/.rakudobrew/moar-2017.11/install/share/perl6/site/sources/B1DA29286A7DB5390F71562CEDB662FE3DFEE15B (Net::AMQP) line 162
```

Is this the correct usage or did I encounter a bug?

**Comment by jonathanstowe** [comment]
Arguably a bug, it appears that RabbitMQ doesn't like the first "prefetch_size" argument:

```
=ERROR REPORT==== 18-Dec-2017::14:55:30 ===
Error on AMQP connection <0.29288.0> (127.0.0.1:41722 -> 127.0.0.1:5672, vhost: '/', user: 'guest', state: running), channel 1:
operation basic.qos caused a connection exception not_implemented: "prefetch_size!=0 (10)"
```
I've tried a number of differently values with the same result,  only 0 seems to be accepted.  I'll dig aroiund but I suspect that it may be that we shouldn't even offer the option of ```prefetch_size``` and always send 0   The note on ```basic.qos``` in https://www.rabbitmq.com/specification.html#release-version-mapping seems to suggest as much: "Prefetch size limits are not implemented.".  And it would also appear that the Java library  ```basicQos``` method only takes the count and not a size argument.

I'll take a better look later (and add some tests as this clearly isn't being tested properly.)

**Comment by abraxxa** [comment]
Indeed, zero works here too, thanks!
From the RabbitMQ docs I wasn't able to understand the difference between the two so I've chosen the same value for both.

**Comment by jonathanstowe** [comment]
I actually started making a fix for this such that it only offers the prefetch count argument and had forgotten until just now.  I'll make the two argument deprecated for this release.

**Comment by jonathanstowe** [comment]
The v0.1.11 should have the above described fix if you're happy please feel free to close.
